"""
HealthLens AI — Agent 2: Plain-language Summary + Chat
Turns structured extraction into detailed, human-friendly explanations.
"""

import os
import json
import re
import logging
from groq import Groq
from models import (
    ExtractionResult, ComparisonResult, RecommendationResult,
    InsightCard, SpecialistRecommendation, TestStatus
)

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "⚕️ This analysis is generated by AI for informational purposes only. "
    "It is NOT a medical diagnosis. Always consult a qualified doctor before making any health decisions."
)

SPECIALIST_MAP = {
    "hemoglobin": ("Hematologist", "Abnormal hemoglobin (blood count)"),
    "wbc": ("Hematologist / General Physician", "Abnormal white blood cell count"),
    "rbc": ("Hematologist", "Abnormal red blood cell count"),
    "platelets": ("Hematologist", "Abnormal platelet count"),
    "glucose": ("Endocrinologist / Diabetologist", "Blood sugar abnormality"),
    "hba1c": ("Endocrinologist / Diabetologist", "Diabetes control marker (HbA1c) abnormal"),
    "tsh": ("Endocrinologist", "Thyroid function abnormal"),
    "creatinine": ("Nephrologist", "Kidney function marker abnormal"),
    "urea": ("Nephrologist", "Kidney function marker abnormal"),
    "cholesterol": ("Cardiologist / Lipidologist", "Cholesterol level abnormal"),
    "triglycerides": ("Cardiologist / Lipidologist", "Triglycerides abnormal"),
    "ldl": ("Cardiologist", "LDL (bad cholesterol) abnormal"),
    "hdl": ("Cardiologist", "HDL (good cholesterol) abnormal"),
    "alt": ("Hepatologist / Gastroenterologist", "Liver enzyme abnormal"),
    "ast": ("Hepatologist / Gastroenterologist", "Liver enzyme abnormal"),
    "bilirubin": ("Hepatologist", "Bilirubin abnormal"),
    "uric acid": ("Rheumatologist / Nephrologist", "Uric acid abnormal"),
    "sodium": ("Nephrologist / General Physician", "Electrolyte (sodium) imbalance"),
    "potassium": ("Cardiologist / Nephrologist", "Electrolyte (potassium) imbalance"),
    "vitamin d": ("Endocrinologist / General Physician", "Vitamin D deficiency"),
    "vitamin b12": ("Neurologist / General Physician", "Vitamin B12 deficiency"),
    "neutrophil": ("Hematologist / General Physician", "Neutrophil count abnormal"),
    "lymphocyte": ("Hematologist / Immunologist", "Lymphocyte count abnormal"),
    "mcv": ("Hematologist", "Red cell size (MCV) abnormal — possible anemia"),
    "mch": ("Hematologist", "Hemoglobin per cell (MCH) abnormal"),
    "mchc": ("Hematologist", "Hemoglobin concentration (MCHC) abnormal"),
    "rdw": ("Hematologist", "Red cell distribution width (RDW) abnormal"),
    "hct": ("Hematologist", "Hematocrit abnormal"),
    "haematocrit": ("Hematologist", "Hematocrit abnormal"),
    "haemoglobin": ("Hematologist", "Hemoglobin abnormal"),
    "mpv": ("Hematologist", "Mean platelet volume (MPV) abnormal"),
}

# ── Summary Prompt ─────────────────────────────────────────────────────────────

SUMMARY_SYSTEM = """You are HealthLens AI — a warm, knowledgeable health assistant who explains medical reports to patients in the clearest, most helpful way possible.

YOUR MISSION: Transform medical jargon into plain, friendly English that anyone can understand — like a doctor friend explaining results over coffee.

STRICT RULES:
1. Use the exact test values from the JSON — never invent numbers.
2. USE your medical knowledge freely to explain WHAT each test measures and WHY it matters.
3. For every test: explain (a) what it measures simply, (b) what the patient's specific number means, (c) whether it's reassuring or needs attention.
4. NORMAL results → be warm and reassuring: "Great news — your [X] is in the healthy range."
5. ABNORMAL results → explain clearly without panic: what it could mean, why a doctor should review it.
6. NEVER diagnose. Say "this may suggest" or "your doctor will want to check for".
7. plain_summary must be 3-5 natural sentences: who is this report for, what kind of report, overall health picture.
8. Every what_it_means must be at least 2 full sentences — specific, helpful, and in plain English.
9. Lifestyle tips must be concrete and specific to the actual abnormal finding.
10. Next steps must be actionable, not generic.

TONE: Warm, clear, human. Patients are worried — be the calm voice that helps them understand."""

SUMMARY_USER = """Analyze this medical report data and generate a detailed patient-friendly summary.

REPORT DATA (use these exact values):
{extraction_json}

COMPARISON WITH PREVIOUS (if any):
{comparison_json}

Generate response in this EXACT JSON format (no text before or after):

{{
  "plain_summary": "3-5 natural sentences: what type of report, for whom, when, and the overall health picture in plain English",
  "key_insights": [
    {{
      "title": "Plain English test name (e.g. 'Hemoglobin — Oxygen Carrier' not just 'HGB')",
      "value": "exact value with unit from report",
      "status": "normal|high|low|abnormal|critical|unknown",
      "plain_explanation": "One clear sentence: what does this test actually measure? Use a simple analogy if helpful.",
      "what_it_means": "2-3 sentences specific to THIS patient's value: Is it good or concerning? What does this number mean for their health? If abnormal, what could it suggest (without diagnosing)?"
    }}
  ],
  "specialist_recommendations": [
    {{
      "specialist_type": "Name of specialist",
      "reason": "Plain English reason — which test is abnormal and why this specialist helps",
      "urgency": "urgent|soon|routine|not_required"
    }}
  ],
  "lifestyle_notes": [
    "Specific, practical tip directly related to an abnormal finding. E.g.: 'Your hemoglobin is low — eating iron-rich foods like spinach, lentils, and red meat can help raise it.'"
  ],
  "next_steps": [
    "Concrete action. E.g.: 'Book an appointment with a hematologist to discuss your low hemoglobin and platelet count.' NOT generic advice like 'consult a doctor'."
  ]
}}

Include ALL tests from the data. Make every explanation genuinely helpful."""


# ── Chat Prompt ────────────────────────────────────────────────────────────────

CHAT_SYSTEM = """You are HealthLens AI, a friendly health assistant helping a patient understand their medical report.

RULES:
1. Answer based on the report data below AND your medical knowledge.
2. When asked about a specific test: explain what it measures, what the patient's value means, and whether it's concerning.
3. Never diagnose. Say "this may suggest" or "your doctor will want to check."
4. Never recommend specific medications or doses.
5. Be warm, clear, thorough. Use simple English. Explain all medical terms.
6. End with: "Remember to discuss this with your doctor for personalized medical advice."

PATIENT'S REPORT:
{report_context}"""

CHAT_USER = "Patient question: {question}\n\nAnswer clearly in plain English, explaining any medical terms."


class Agent2Recommender:
    def __init__(self):
        api_key = os.getenv("GROQ_API_KEY")
        if not api_key or api_key == "your_groq_api_key_here":
            raise ValueError(
                "GROQ_API_KEY is not configured. "
                "Open the .env file and replace 'your_groq_api_key_here' with your actual key from https://console.groq.com"
            )
        self.client = Groq(api_key=api_key)
        self.model_accurate = os.getenv("GROQ_MODEL_ACCURATE", "llama-3.3-70b-versatile")
        self.model_fast = os.getenv("GROQ_MODEL_FAST", "llama-3.3-70b-versatile")

    def recommend(self, extraction: ExtractionResult, comparison: ComparisonResult) -> RecommendationResult:
        extraction_json = json.dumps(extraction.model_dump(), indent=2, default=str)
        comparison_json = json.dumps(comparison.model_dump(), indent=2, default=str)

        user_msg = SUMMARY_USER.format(
            extraction_json=extraction_json[:9000],
            comparison_json=comparison_json[:2000],
        )

        try:
            response = self.client.chat.completions.create(
                model=self.model_accurate,
                messages=[
                    {"role": "system", "content": SUMMARY_SYSTEM},
                    {"role": "user", "content": user_msg},
                ],
                temperature=0.2,
                max_tokens=4000,
                response_format={"type": "json_object"},
            )
            raw = response.choices[0].message.content
            data = self._safe_parse_json(raw)
            return self._build_result(data, extraction)

        except Exception as e:
            logger.error(f"Agent 2 error: {e}")
            return self._fallback_result(extraction, str(e))

    def chat(self, extraction: ExtractionResult, question: str) -> str:
        # Build rich context
        parts = []
        if extraction.patient.name:
            parts.append(f"Patient: {extraction.patient.name}")
        if extraction.patient.age:
            parts.append(f"Age: {extraction.patient.age}")
        if extraction.patient.gender:
            parts.append(f"Gender: {extraction.patient.gender}")
        if extraction.document_date:
            parts.append(f"Report date: {extraction.document_date}")
        if extraction.lab_name:
            parts.append(f"Lab: {extraction.lab_name}")
        parts.append(f"Document type: {extraction.document_type.value}")

        if extraction.tests:
            parts.append("\nTest Results:")
            for t in extraction.tests[:30]:
                ref = f" (ref: {t.reference_range})" if t.reference_range else ""
                parts.append(f"  • {t.test_name}: {t.value} {t.unit or ''} [{t.status.value.upper()}]{ref}")

        if extraction.medicines:
            parts.append("\nMedicines:")
            for m in extraction.medicines[:15]:
                parts.append(f"  • {m.name} {m.dosage or ''} {m.frequency or ''}".strip())

        if extraction.diagnoses:
            parts.append(f"\nDiagnoses: {', '.join(extraction.diagnoses)}")

        if extraction.doctor_notes:
            parts.append(f"\nDoctor notes: {extraction.doctor_notes}")

        report_context = "\n".join(parts)

        try:
            response = self.client.chat.completions.create(
                model=self.model_fast,
                messages=[
                    {"role": "system", "content": CHAT_SYSTEM.format(report_context=report_context)},
                    {"role": "user", "content": CHAT_USER.format(question=question)},
                ],
                temperature=0.2,
                max_tokens=1500,
            )
            answer = response.choices[0].message.content.strip()
            return f"{answer}\n\n{DISCLAIMER}"

        except Exception as e:
            logger.error(f"Chat error: {e}")
            if "api_key" in str(e).lower() or "authentication" in str(e).lower():
                return (
                    "❌ API key error: Your GROQ_API_KEY in the .env file is invalid or not set. "
                    "Get a free key from https://console.groq.com and update the .env file, then restart the server."
                )
            return f"Sorry, I couldn't answer that question right now. Error: {str(e)}\n\n{DISCLAIMER}"

    # ── Helpers ────────────────────────────────────────────────────────────────

    def _safe_parse_json(self, raw: str) -> dict:
        try:
            return json.loads(raw)
        except json.JSONDecodeError:
            match = re.search(r"\{.*\}", raw, re.DOTALL)
            if match:
                try:
                    return json.loads(match.group())
                except Exception:
                    pass
        return {}

    def _build_result(self, data: dict, extraction: ExtractionResult) -> RecommendationResult:
        status_map = {
            "normal": TestStatus.NORMAL, "high": TestStatus.HIGH, "low": TestStatus.LOW,
            "abnormal": TestStatus.ABNORMAL, "critical": TestStatus.CRITICAL,
        }

        insights = []
        for item in (data.get("key_insights") or [])[:20]:
            status = status_map.get(str(item.get("status", "")).lower(), TestStatus.UNKNOWN)
            insights.append(InsightCard(
                title=str(item.get("title", "")),
                value=str(item.get("value", "")),
                status=status,
                plain_explanation=str(item.get("plain_explanation", "")),
                what_it_means=str(item.get("what_it_means", "")),
            ))

        # Specialist recommendations
        specialists = []
        seen = set()

        for s in (data.get("specialist_recommendations") or [])[:6]:
            spec_type = str(s.get("specialist_type", ""))
            if spec_type and spec_type not in seen:
                urgency = s.get("urgency", "routine")
                if urgency not in ("urgent", "soon", "routine", "not_required"):
                    urgency = "routine"
                specialists.append(SpecialistRecommendation(
                    specialist_type=spec_type,
                    reason=str(s.get("reason", "")),
                    urgency=urgency,
                ))
                seen.add(spec_type)

        # Rule-based fallback for any abnormal tests not caught by LLM
        for test in extraction.tests:
            if test.status in (TestStatus.HIGH, TestStatus.LOW, TestStatus.ABNORMAL, TestStatus.CRITICAL):
                name_lower = test.test_name.lower()
                for key, (spec, reason) in SPECIALIST_MAP.items():
                    if key in name_lower and spec not in seen:
                        urgency = "urgent" if test.status == TestStatus.CRITICAL else "soon"
                        specialists.append(SpecialistRecommendation(
                            specialist_type=spec,
                            reason=f"{reason}: {test.test_name} = {test.value} {test.unit or ''}",
                            urgency=urgency,
                        ))
                        seen.add(spec)
                        break

        return RecommendationResult(
            plain_summary=str(data.get("plain_summary", "Report analyzed. See test insights below.")),
            key_insights=insights,
            specialist_recommendations=specialists,
            lifestyle_notes=[str(n) for n in (data.get("lifestyle_notes") or [])],
            next_steps=[str(s) for s in (data.get("next_steps") or [])],
            disclaimer=DISCLAIMER,
        )

    def _fallback_result(self, extraction: ExtractionResult, error: str = "") -> RecommendationResult:
        abnormal = [t for t in extraction.tests if t.status in (TestStatus.HIGH, TestStatus.LOW, TestStatus.ABNORMAL, TestStatus.CRITICAL)]
        normal = [t for t in extraction.tests if t.status == TestStatus.NORMAL]

        if "api_key" in error.lower() or "authentication" in error.lower() or "groq_api_key" in error.lower():
            summary = (
                "❌ Cannot generate AI summary — your GROQ_API_KEY is not configured. "
                "Open the .env file and replace 'your_groq_api_key_here' with your actual key "
                "from https://console.groq.com, then restart the server."
            )
        elif extraction.tests:
            summary = (
                f"This is a {extraction.document_type.value.replace('_', ' ')} report. "
                f"{len(extraction.tests)} tests were extracted. "
                f"{len(abnormal)} test(s) showed abnormal values. "
                f"{len(normal)} test(s) were within normal range."
            )
        else:
            summary = "Report processed but no test values could be extracted. Please check that your GROQ_API_KEY is set correctly in the .env file."

        insights = [
            InsightCard(
                title=t.test_name,
                value=f"{t.value} {t.unit or ''}".strip(),
                status=t.status,
                plain_explanation=f"Test: {t.test_name}",
                what_it_means=f"Value is {t.status.value}. Reference range: {t.reference_range or 'Not shown'}.",
            )
            for t in extraction.tests[:15]
        ]

        return RecommendationResult(
            plain_summary=summary,
            key_insights=insights,
            next_steps=[
                "Set up your GROQ_API_KEY in the .env file for full AI-powered analysis.",
                "Consult your doctor to discuss these test results."
            ],
            disclaimer=DISCLAIMER,
        )
