"""
HealthLens AI — Agent 2: Recommendation + Chat Agent

PURPOSE:
  Takes VERIFIED structured extraction → produces plain-language health insights
  and specialist recommendations. Also handles follow-up chat questions.

SAFETY DESIGN:
  - Only uses data from the verified extraction (Agent 1 + Agent 3 output)
  - Cannot add information not in the structured data
  - Refuses to guess when data is missing
  - Appends disclaimer on every response
  - Chat responses are grounded ONLY in the report context

MODEL: llama-3.3-70b-versatile for summaries, llama-3.1-8b-instant for quick chat
"""

import os
import json
import re
import logging
from groq import Groq
from models import (
    ExtractionResult, ComparisonResult, RecommendationResult,
    InsightCard, SpecialistRecommendation, TestStatus
)

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "⚕️ IMPORTANT: This analysis is generated by AI for informational purposes only. "
    "It is NOT a medical diagnosis or medical advice. "
    "Always consult a qualified, registered doctor before making any health or treatment decisions."
)

# ─── Specialist Mapping ────────────────────────────────────────────────────────
SPECIALIST_MAP = {
    "hemoglobin": ("Hematologist", "Abnormal blood count values"),
    "wbc": ("Hematologist / Physician", "White blood cell abnormality"),
    "rbc": ("Hematologist", "Red blood cell abnormality"),
    "platelets": ("Hematologist", "Platelet count abnormality"),
    "glucose": ("Endocrinologist / Diabetologist", "Blood sugar abnormality"),
    "hba1c": ("Endocrinologist / Diabetologist", "HbA1c (diabetes control marker) abnormality"),
    "tsh": ("Endocrinologist", "Thyroid function abnormality"),
    "creatinine": ("Nephrologist", "Kidney function abnormality"),
    "urea": ("Nephrologist", "Kidney function marker abnormality"),
    "cholesterol": ("Cardiologist / Lipidologist", "Lipid profile abnormality"),
    "triglycerides": ("Cardiologist / Lipidologist", "Triglyceride level abnormality"),
    "ldl": ("Cardiologist", "LDL cholesterol abnormality"),
    "hdl": ("Cardiologist", "HDL cholesterol abnormality"),
    "alt": ("Hepatologist / Gastroenterologist", "Liver enzyme abnormality"),
    "ast": ("Hepatologist / Gastroenterologist", "Liver enzyme abnormality"),
    "bilirubin": ("Hepatologist / Gastroenterologist", "Bilirubin level abnormality"),
    "uric acid": ("Rheumatologist / Nephrologist", "Uric acid level abnormality"),
    "sodium": ("Nephrologist / Physician", "Electrolyte imbalance"),
    "potassium": ("Cardiologist / Nephrologist", "Electrolyte imbalance"),
    "vitamin d": ("Endocrinologist / General Physician", "Vitamin D deficiency"),
    "vitamin b12": ("Neurologist / General Physician", "Vitamin B12 deficiency"),
    "ecg": ("Cardiologist", "ECG abnormality"),
    "echo": ("Cardiologist", "Echocardiogram finding"),
}

URGENCY_KEYWORDS = {
    "critical": "urgent",
    "panic": "urgent",
    "very high": "urgent",
    "very low": "urgent",
    "severe": "urgent",
}


# ─── Summary Prompt ────────────────────────────────────────────────────────────

SUMMARY_SYSTEM = """You are HealthLens AI, a friendly and knowledgeable health assistant that explains medical reports to patients in plain, simple English. Think of yourself as a caring doctor friend who explains reports in a way anyone can understand.

YOUR GOAL: Give the patient a thorough, clear, educational explanation of their report — what each test is, what the value means, and what they should do next.

RULES:
1. USE YOUR MEDICAL KNOWLEDGE freely to explain what each test measures, why it matters, and what the value means for the patient's health. Do not limit yourself to only what's in the JSON.
2. GROUND YOUR RESPONSE in the actual values from the JSON — never invent values.
3. If a test value is missing or confidence is LOW, say "Not clearly readable" — do not guess the value.
4. Use SIMPLE LANGUAGE a non-medical person can understand. Avoid jargon. If you must use a medical term, explain it in brackets.
5. For EACH TEST: explain (a) what the test measures in one simple sentence, (b) what this patient's specific value means, and (c) whether it's a concern or reassuring.
6. For ABNORMAL values: explain clearly WHY it matters, what it could indicate (without diagnosing), and what kind of doctor can help.
7. For NORMAL values: be reassuring and tell the patient it's good news.
8. Do NOT make a definitive diagnosis. Say "this could suggest" or "your doctor will want to check for".
9. Be warm and caring. Patients are often worried about their reports — reassure them where appropriate but be honest about concerns.
10. Always end with practical next steps.

TONE: Warm, clear, reassuring but honest. Like a knowledgeable friend explaining over a cup of tea."""

SUMMARY_USER = """Here is the verified medical report data. Generate a thorough, patient-friendly summary.

VERIFIED REPORT DATA:
{extraction_json}

COMPARISON WITH PREVIOUS REPORT (if any):
{comparison_json}

Generate a detailed response in this EXACT JSON format:

{{
  "plain_summary": "3-4 sentences explaining what this report is, who it's for, when it was done, and the overall picture of the patient's health from this report",
  "key_insights": [
    {{
      "title": "test name in plain English (e.g. 'Blood Sugar Test' not just 'Glucose')",
      "value": "value with unit",
      "status": "normal|high|low|abnormal|critical|unknown",
      "plain_explanation": "What this test measures in 1 simple sentence that anyone can understand. Use an analogy if helpful.",
      "what_it_means": "2-3 sentences: What does THIS patient's specific value mean? Is it good, mildly concerning, or seriously abnormal? What could a high/low value indicate (without diagnosing)? Be specific about the number."
    }}
  ],
  "specialist_recommendations": [
    {{
      "specialist_type": "type of specialist",
      "reason": "clear reason in plain English — what abnormal test is driving this recommendation",
      "urgency": "urgent|soon|routine|not_required"
    }}
  ],
  "lifestyle_notes": ["practical, specific lifestyle tip directly related to an abnormal finding — e.g. 'Since your blood sugar is high, reducing rice, bread, and sugary drinks can help bring it down'"],
  "next_steps": ["concrete, specific action the patient should take — not generic advice"]
}}

Return ONLY valid JSON. Make the explanations thorough — patients deserve to understand their own health."""


# ─── Chat Prompt ──────────────────────────────────────────────────────────────

CHAT_SYSTEM = """You are HealthLens AI, a friendly health assistant helping a patient understand their medical report.

YOUR JOB: Answer the patient's question in plain, simple English. Be helpful, warm, and thorough.

RULES:
1. Use the report data provided as your PRIMARY source for specific values, test results, and medicines.
2. You CAN and SHOULD use your general medical knowledge to explain what tests mean, what values indicate, what medicines are used for, etc.
3. If the patient asks about a specific value from their report, explain both the value AND what it means in plain English.
4. If the patient asks about something completely unrelated to health, gently redirect them.
5. Do NOT make a definitive diagnosis. Say "this could suggest" or "your doctor will want to check".
6. Do NOT recommend specific medications or dosages.
7. Keep answers clear and easy to understand — like explaining to a knowledgeable friend.
8. Be reassuring but honest. If something is concerning, explain it gently.
9. End every response with a brief reminder to consult their doctor for medical decisions.

REPORT CONTEXT:
{report_context}"""

CHAT_USER = """Patient question: {question}

Please give a clear, thorough answer in plain English. Explain any medical terms used."""


class Agent2Recommender:
    def __init__(self):
        api_key = os.getenv("GROQ_API_KEY")
        if not api_key:
            raise ValueError("GROQ_API_KEY not set")
        self.client = Groq(api_key=api_key)
        self.model_accurate = os.getenv("GROQ_MODEL_ACCURATE", "llama-3.3-70b-versatile")
        self.model_fast = os.getenv("GROQ_MODEL_FAST", "llama-3.3-70b-versatile")

    def recommend(
        self,
        extraction: ExtractionResult,
        comparison: ComparisonResult,
    ) -> RecommendationResult:
        """Generate full summary + recommendations from verified data."""
        extraction_dict = extraction.model_dump()
        extraction_json = json.dumps(extraction_dict, indent=2, default=str)
        comparison_dict = comparison.model_dump()
        comparison_json = json.dumps(comparison_dict, indent=2, default=str)

        user_msg = SUMMARY_USER.format(
            extraction_json=extraction_json[:8000],
            comparison_json=comparison_json[:2000],
        )

        try:
            response = self.client.chat.completions.create(
                model=self.model_accurate,
                messages=[
                    {"role": "system", "content": SUMMARY_SYSTEM},
                    {"role": "user", "content": user_msg},
                ],
                temperature=0.2,
                max_tokens=4096,
                response_format={"type": "json_object"},
            )
            raw = response.choices[0].message.content
            data = self._safe_parse_json(raw)
            result = self._build_result(data, extraction)
            return result

        except Exception as e:
            logger.error(f"Agent 2 error: {e}")
            # Fallback: build basic result from extraction data without LLM
            return self._fallback_result(extraction)

    def chat(self, extraction: ExtractionResult, question: str) -> str:
        """Answer a single follow-up question about the report."""
        # Build concise context
        context_parts = []
        if extraction.patient.name:
            context_parts.append(f"Patient: {extraction.patient.name}")
        if extraction.document_date:
            context_parts.append(f"Report date: {extraction.document_date}")
        context_parts.append(f"Document type: {extraction.document_type.value}")
        if extraction.lab_name:
            context_parts.append(f"Lab: {extraction.lab_name}")
        if extraction.tests:
            context_parts.append("Test results (name: value unit [status] | reference range):")
            for t in extraction.tests[:25]:  # Limit for context window
                ref = f" | ref: {t.reference_range}" if t.reference_range else ""
                context_parts.append(f"  - {t.test_name}: {t.value} {t.unit or ''} [{t.status.value}]{ref}")
        if extraction.medicines:
            context_parts.append("Medicines:")
            for m in extraction.medicines[:10]:
                context_parts.append(f"  - {m.name} {m.dosage or ''} {m.frequency or ''}")
        if extraction.diagnoses:
            context_parts.append(f"Diagnoses: {', '.join(extraction.diagnoses)}")

        report_context = "\n".join(context_parts)

        try:
            response = self.client.chat.completions.create(
                model=self.model_fast,
                messages=[
                    {"role": "system", "content": CHAT_SYSTEM.format(report_context=report_context)},
                    {"role": "user", "content": CHAT_USER.format(question=question)},
                ],
                temperature=0.2,
                max_tokens=1200,
            )
            answer = response.choices[0].message.content.strip()
            return f"{answer}\n\n{DISCLAIMER}"

        except Exception as e:
            logger.error(f"Agent 2 chat error: {e}")
            return f"I encountered an error answering your question. Please consult your doctor directly.\n\n{DISCLAIMER}"

    # ──────────────────────────────────────────────────────────────────────────
    # Helpers
    # ──────────────────────────────────────────────────────────────────────────

    def _safe_parse_json(self, raw: str) -> dict:
        try:
            return json.loads(raw)
        except json.JSONDecodeError:
            match = re.search(r"\{.*\}", raw, re.DOTALL)
            if match:
                try:
                    return json.loads(match.group())
                except Exception:
                    pass
        return {}

    def _build_result(self, data: dict, extraction: ExtractionResult) -> RecommendationResult:
        # Key insights
        insights = []
        for item in (data.get("key_insights") or [])[:15]:
            status_map = {
                "normal": TestStatus.NORMAL, "high": TestStatus.HIGH,
                "low": TestStatus.LOW, "abnormal": TestStatus.ABNORMAL,
                "critical": TestStatus.CRITICAL,
            }
            status = status_map.get(str(item.get("status", "")).lower(), TestStatus.UNKNOWN)
            insights.append(InsightCard(
                title=str(item.get("title", "")),
                value=str(item.get("value", "")),
                status=status,
                plain_explanation=str(item.get("plain_explanation", "")),
                what_it_means=str(item.get("what_it_means", "")),
            ))

        # Specialist recommendations — merge LLM + rule-based
        specialists = []
        seen_specialists = set()

        # LLM recommendations
        for s in (data.get("specialist_recommendations") or [])[:5]:
            spec_type = str(s.get("specialist_type", ""))
            if spec_type and spec_type not in seen_specialists:
                urgency = s.get("urgency", "routine")
                if urgency not in ("urgent", "soon", "routine", "not_required"):
                    urgency = "routine"
                specialists.append(SpecialistRecommendation(
                    specialist_type=spec_type,
                    reason=str(s.get("reason", "")),
                    urgency=urgency,
                ))
                seen_specialists.add(spec_type)

        # Rule-based fallback for abnormal tests not covered by LLM
        for test in extraction.tests:
            if test.status in (TestStatus.HIGH, TestStatus.LOW, TestStatus.ABNORMAL, TestStatus.CRITICAL):
                name_lower = test.test_name.lower()
                for key, (spec, reason) in SPECIALIST_MAP.items():
                    if key in name_lower and spec not in seen_specialists:
                        urgency = "urgent" if test.status == TestStatus.CRITICAL else "routine"
                        for kw, urg in URGENCY_KEYWORDS.items():
                            if kw in test.value.lower():
                                urgency = urg
                                break
                        specialists.append(SpecialistRecommendation(
                            specialist_type=spec,
                            reason=f"{reason}: {test.test_name} = {test.value}",
                            urgency=urgency,
                        ))
                        seen_specialists.add(spec)
                        break

        return RecommendationResult(
            plain_summary=str(data.get("plain_summary", "Report analyzed. See insights below.")),
            key_insights=insights,
            specialist_recommendations=specialists,
            lifestyle_notes=[str(n) for n in (data.get("lifestyle_notes") or [])],
            next_steps=[str(s) for s in (data.get("next_steps") or [])],
            disclaimer=DISCLAIMER,
        )

    def _fallback_result(self, extraction: ExtractionResult) -> RecommendationResult:
        """Basic result without LLM, built from extraction data."""
        abnormal = [t for t in extraction.tests if t.status in (TestStatus.HIGH, TestStatus.LOW, TestStatus.ABNORMAL, TestStatus.CRITICAL)]
        normal = [t for t in extraction.tests if t.status == TestStatus.NORMAL]

        summary_parts = [f"This is a {extraction.document_type.value.replace('_', ' ')}."]
        if abnormal:
            summary_parts.append(f"{len(abnormal)} test(s) showed abnormal values.")
        if normal:
            summary_parts.append(f"{len(normal)} test(s) were within normal range.")

        insights = [
            InsightCard(
                title=t.test_name,
                value=f"{t.value} {t.unit or ''}".strip(),
                status=t.status,
                plain_explanation=f"Test: {t.test_name}",
                what_it_means=f"Value is {t.status.value}. Reference range: {t.reference_range or 'Not available'}.",
            )
            for t in extraction.tests[:10]
        ]

        return RecommendationResult(
            plain_summary=" ".join(summary_parts),
            key_insights=insights,
            next_steps=["Please consult your doctor to discuss these results."],
            disclaimer=DISCLAIMER,
        )
